#!/bin/bash

# Get scripts directory.
DIR=$(cd $(dirname "$0"); pwd)


# Print out info to the console
echo ''
echo 'BDW - Simple Web Server for Week 6 Class'
echo ''
echo 'Get started by opening your browser and going to:'
echo 'http://localhost:8000/'
echo ''
echo ''


# run server from the correct directory
cd $DIR
php -S localhost:8000
